// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhoruBackend.Data;

#nullable disable

namespace WhoruBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230913171236_initialDb2")]
    partial class initialDb2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhoruBackend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 896, DateTimeKind.Utc).AddTicks(834),
                            RoleName = "Admin",
                            UpdatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 896, DateTimeKind.Utc).AddTicks(837)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 896, DateTimeKind.Utc).AddTicks(839),
                            RoleName = "User",
                            UpdatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 896, DateTimeKind.Utc).AddTicks(840)
                        });
                });

            modelBuilder.Entity("WhoruBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 896, DateTimeKind.Utc).AddTicks(914),
                            Email = "nmc0401@gmail.com",
                            Password = "AQAQJwAAzGLO9OIIBakdzPH9XmAx4HJf2QR0k8xH0zvMHVuHWtgE6ZYDUaJRj/ClSgyLWXwW",
                            RoleId = 1,
                            UpdatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 896, DateTimeKind.Utc).AddTicks(915),
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 910, DateTimeKind.Utc).AddTicks(5746),
                            Email = "20110455@gmail.com",
                            Password = "AQAQJwAA3BHuUebF5B/gkicYRypmwoQJkounPzzPujCkQygyinhKIPMfkBjx1VV69JFLAB7x",
                            RoleId = 1,
                            UpdatedDate = new DateTime(2023, 9, 13, 17, 12, 35, 910, DateTimeKind.Utc).AddTicks(5751),
                            UserName = "admin_2"
                        });
                });

            modelBuilder.Entity("WhoruBackend.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "Link hinh anh :>",
                            FullName = "Nguyen Minh Cuong",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "Link hinh anh :>",
                            FullName = "Nguyen Minh Nhut",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WhoruBackend.Models.UserInfo", b =>
                {
                    b.HasOne("WhoruBackend.Models.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("WhoruBackend.Models.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhoruBackend.Models.User", b =>
                {
                    b.Navigation("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
